### ISSUE TITLE
Only run CI checks when appropriate files have changed

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#14]
E.g. don't run code coverage or the test suite if only the docs changed (or vice-versa).

**Comment by berkerpeksag** [comment]
This is now done. @brettcannon could you please close this?

Side note: Should we allow "Core developers" team to close issues on this repo?

**Comment by brettcannon** [comment]
Closed and now the core team has write permissions (just simply forgot to add the team).

**Comment by brettcannon** [comment]
And thanks for the change! I'm sure not only PR submitters appreciate the faster turn-around but I bet Travis appreciates us using less free resources. 😄

**Comment by ammaraskar** [comment]
I don't think the Doc only test works. See this PR here: https://github.com/python/cpython/pull/3072
The travis run: https://travis-ci.org/python/cpython/builds/263366915 (and it's [console log](https://travis-ci.org/python/cpython/jobs/263366916#L435))

It triggered a full code rebuild and test even though the only thing that has changed is `Doc/library/socket.rst`

**Comment by brettcannon** [comment]
It was working but it seems something has changed such that it didn't succeed in this case.

**Comment by ammaraskar** [comment]
I've done some investigating and this is due to how Travis gets the merged code from Github.

Following the sequence of commands it used to get the repo here, it went:

1. `git clone --depth=50 https://github.com/ammaraskar/cpython.git`
2. `git fetch origin +refs/pull/5/merge`
3. `git checkout -qf FETCH_HEAD`

I replicated these commands locally and ran `git log` and the problem became obvious. Github in their special `refs/pull/*/merge` branch creates a merge commit which means at that point this git log looks something like:

```
472056eb60b0601dcded798229bebbddfd307945
```

**Comment by brettcannon** [comment]
OK, so it's basically it's imperfect but isn't hurting anything. Thanks for the detailed report, @ammaraskar ! I'm going to close this again and we can just live with occasionally building more than necessary.

**Comment by ammaraskar** [comment]
There's a way around it, I opened up a PR to fix it: https://github.com/python/cpython/issues/3129

Whether it's worth the added complexity to the build process, that I don't know.
