### ISSUE TITLE
Permalinks for source code

### ISSUE THREAD

**Issue by rhettinger** [python/core-workflow#181]
Source code permalinks would be useful for tracker discussions, bug reports, blog posts, and StackOverflow answers.  Ideally, it should be independent of the current version control system in use:

     https://viewcode.python.org/cpython/2.7.13/Lib/functools?from=115&to=120

**Comment by ezio-melotti** [comment]
Having permalinks is not difficult while resolving URLs, but it is while creating them.  While resolving URL, we can always redirect to GitHub or somewhere else. However people are currently using GitHub to look at the code, so if they try to link at some piece of code they will get a github.org link, not a *.python.org one.

When we moved from hg.python.org we were able to set up a redirect script to point on GitHub (this hasn't been done yet but probably should), but If we move out from GitHub we will not be able to do the same.

**Comment by brettcannon** [comment]
Just an FYI, if you're looking at source code in the GitHub UI, you can press `y` and you will get a URL that is tied to the revision you're viewing. This also works with selected lines and such.

**Comment by hugovk** [comment]
In addition to pressing `y`, you can click the ellipsis by the line numbers and select "Copy permalink":

<img width="327" alt="image" src="https://user-images.githubusercontent.com/1324225/213998384-42395619-16e2-483a-9d15-042ff8bbe2c4.png">

And multiline highlights are possible using `#Lx-#Ly`.

Some examples with GitHub:

* Single line: https://github.com/python/cpython/blob/main/Lib/_pylong.py#L84
* Multiple lines: https://github.com/python/cpython/blob/main/Lib/_pylong.py#L84-L86 
* Single line permalink: https://github.com/python/cpython/blob/807d6b576fa37f3ab7eb951297cb365c0c198595/Lib/_pylong.py#L84
* Multiline permalink: https://github.com/python/cpython/blob/807d6b576fa37f3ab7eb951297cb365c0c198595/Lib/_pylong.py#L84-L86

GitHub Docs:

* https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet

---

There's not been much discussion on this issue since it was created 5 years ago, I guess there's not been too much need for a independent host to point to source code, and people are fine linking directly to GitHub?

Shall we close this issue?

**Comment by CAM-Gerlach** [comment]
SGTM, FWIW
