### ISSUE TITLE
blurb loses information when merge

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/core-workflow#210]
When blurb merges multiple entries into a single file it loses information if the description contains several paragraphs. Only the first paragraph is saved.

For example see python/cpython@3b43bfaae665ab784ef67cefc3a3f95a75aafdc4, the descriptions of bpo-31993, bpo-26439, bpo-32357. I'm sure there were losses in the past merges too.

**Comment by serhiy-storchaka** [comment]
@larryhastings @ned-deily @benjaminp

**Comment by ned-deily** [comment]
@serhiy-storchaka, those differences are due to my editing, not a bug in blurb.  After having already blurbified of NEWS for 3.7.0a4, I did a final read  of the changelong.html and felt that those particular entries were too long and detailed for the changelog.  Rather than taking the time to do things properly by reverting the release engineering changes, editing the individual NEWS entries, and redoing, I took the short cut of just editing the resultant blurb.   Sorry for the confusion!
