### ISSUE TITLE
Move build status to README.rst?

### ISSUE THREAD

**Issue by zware** [python/core-workflow#22]
The build status tags and links are currently in .github/CONTRIBUTING.rst, which is really only seen when you navigate to it.  Should we move it to README.rst for higher visibility?

**Comment by haypo** [comment]
What is  .github/CONTRIBUTING.rst? Why is it in an hidden directory rather than the root directory?

**Comment by brettcannon** [comment]
The badges moved so I'm closing this.

And to answer Victor's question: .github/CONTRIBUTING.md is what GitHub links to when you open a PR and see the banner saying there are guidelines to submitting a PR. It's not in the top-level directory because there was pushback over a year ago about spewing GitHub-specific files in the top-level directory when it isn't necessary (which it isn't thanks to GitHub supporting the .github/ directory).
