### ISSUE TITLE
Automate the issue creation for PR that don't refer to any existing issue.

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#25]
Brought up by @ezio-melotti in https://github.com/python/devguide/issues/104 :)

**Comment by ezio-melotti** [comment]
If the great majority of PRs refer to a bpo issue, we might just make this completely automated: i.e. if a new PR doesn't refer to any bpo issue, one will be created.

If however people forget to refer to bpo issues or do it wrong, this will end up creating extra issues that we will have to remove manually, so we can't completely automate this.

One option might be to create a bot (or something else), that detects new PRs that are not linked to any bpo issue, and adds a message asking if the user wants to create the issue, with a link to the "new issue" page (I'm assuming there's no way to add a "create issue" button that sends a request via POST, so we are limited to GET).  It's currently possible to pass the title and the body of the message via GET (assuming the message is not too long), but not the PR number.  If updating the PR title retriggers the webhook, users can then submit a PR, click the "new issue" link provided by the bot, create a new issue, and update the PR title in order to link it to the issue.

**Comment by warsaw** [comment]
On Feb 24, 2017, at 08:06 PM, Ezio Melotti wrote:

>If the great majority of PRs refer to a bpo issue, we might just make this
>completely automated: i.e. if a new PR doesn't refer to any bpo issue, one
>will be created.
>
>If however people forget to refer to bpo issues or do it wrong, this will end
>up creating extra issues that we will have to remove manually, so we can't
>completely automate this.
>
>One option might be to create a bot (or something else), that detects new PRs
>that are not linked to any bpo issue, and adds a message asking if the user
>wants to create the issue, with a link to the "new issue" page (I'm assuming
>there's no way to add a "create issue" button that sends a request via POST,
>so we are limited to GET).  It's currently possible to pass the title and the
>body of the message via GET (assuming the message is not too long), but not
>the PR number.  If updating the PR title retriggers the webhook, users can
>then submit a PR, click the "new issue" link provided by the bot, create a
>new issue, and update the PR title in order to link it to the issue.

Yes, I think this is a reasonable way to go.  I'm thinking about something
similar to the CLA bot so we at least have a tag that indicates whether the PR
is linked to a bug.  We wouldn't prevent landing unlinked PRs, but it would be
a good indicator to the submitter and reviewer that we highly prefer bugs for
PRs.  A direct report bug link would be very cool.

**Comment by brettcannon** [comment]
GH-28 ties into this. If we have a bot that always leaves a comment upon PR creation which is either a link to bugs.python.org or a mention that there's no bug and how to create one then this should cover this. Then the bot can automatically add links in the future per PR comments or title changes to pick up when people add issue references.

**Comment by brettcannon** [comment]
Closing this thanks to Bedevere launching.
