### ISSUE TITLE
Create the "Python Triage" team on GitHub. 

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#334]
Give it "Triage" access to CPython.

**Comment by Mariatta** [comment]
Any suggestion of what the team name should be?
`Bug Triager`?
`Python Triagers`? (note that we use `Python core` for core devs)
`Bug Triage`?
???

**Comment by brettcannon** [comment]
`Python triage`?

**Comment by Mariatta** [comment]
Any opinion whether the `Python triage` team should have triage access to CPython repo only, or all the repos that is under `Python core`?

**Comment by aeros167** [comment]
@brettcannon 
> Python triage?

I quite like this name since the proposed role would assist with a variety of PRs and issues, not exclusively bugs (which `Bug traiger` might imply). Following this theme, the name of the group would be the `Python triage team` and the name to use for individuals which have the role would be something like `Python triager`.

@Mariatta 
>Any opinion whether the Python triage team should have triage access to CPython repo only, or all the repos that is under Python core?

Personally, I think that it would be quite useful for the triage team to be able to also assist with devguide and core-workflow. The CPython repo has the highest volume of PRs, but devguide especially has a decent number of issues and PRs that come in periodically. I think it's important for the role to be associated with the Python repos in general, and not just CPython alone.

If it would make the process of implementing the role easier (such as setting up permissions), we could initially start with just CPython, but in general I think it should extend to any active `Python core` repository.

**Comment by aeros167** [comment]
@Mariatta Should I attach the PR for the devguide GitHub label section to this issue or should it be separate?

**Comment by Mariatta** [comment]
Perhaps it's better to link to this issue https://github.com/python/devguide/issues/296
