### ISSUE TITLE
Link to GitHub PR from bpo emails

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#35]
When someone creates a pull request that links to a bpo issue, there would be email sent to the issue subscribers / nosy list, for example:

```
Changes by Mariatta Wijaya <mariatta.wijaya@gmail.com>:


----------
pull_requests: +70
```

1. Does `70` here refer to GitHub pull request number 70? (eg https://github.com/python/cpython/pull/70)
2. Instead of a plaintext `+70`, can it be a link to the said pull request?

Thanks :)

**Comment by ezio-melotti** [comment]
1. The 70 only refers to pull_request item of the tracker, i.e. https://bugs.python.org/pull_request70
  The actual PR number is different, as you can see from the link (in this case is python/cpython#107).
2. These mails are automatically generated, and I'm not aware of a way to change them and insert the link.  It should be possible, but probably it's not too straightforward, and it might not be worth the effort.

**Comment by Mariatta** [comment]
Thanks for the info, @ezio-melotti 
If there's no straightforward way to do it, then let's not bother for now.

**Comment by ncoghlan** [comment]
I'm reopening this, as the status quo is genuinely confusing when one PR references multiple issues - each email has a different numeric identifier for the PR, even if they're all related to the same PR. (I'd be surprised if it ever happens again to the degree it did when the draft NEWS generation PR was closed, but I'd also be surprised if it never happens at all)

Rather than attempting to customise these emails directly, would it possible to turn off email notifications for PR additions and state changes entirely, and instead inject more meaningful comments describing the state change?

**Comment by ezio-melotti** [comment]
If you want to continue the discussion I'd suggest moving it to the meta-tracker:
http://psf.upfronthosting.co.za/roundup/meta/issue624
