### ISSUE TITLE
Should the Tests / Ubuntu (pull_request) not be required on 3.8/3.9 branches?

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#382]
There are a couple PRs that I noticed (there might be more) where automerging was blocked, because it was waiting for the required check: `Tests / Ubuntu (pull_request)` to pass.
Looking at these PRs, it appeared that the `Tests / Ubuntu (pull_request)` were both Skipped on that branch.

https://github.com/python/cpython/pull/22869 [3.8]
https://github.com/python/cpython/pull/22897 [3.9]

Should this check not be required on the 3.9, 3.8 branches?

Todo:

- [ ] Adjust miss-islington to handle skipped tests, instead of expecting all `success` status

**Comment by brettcannon** [comment]
@ambv what's your opinion?

**Comment by ambv** [comment]
This is a bug. The tests are required and I'd prefer it stayed that way. Backports are not always a trivial manner, unrelated commits that were not backported could sometimes be required for a change to work correctly.

The bug is that for changes which don't touch code at all we skip running tests whatsoever and this somehow blocks auto-merging. It shouldn't if the step was skipped.

**Comment by Mariatta** [comment]
Ok I will need to adjust miss-islington to understand that some tests can be `skipped`. Currently it expects all `success` status.

**Comment by AA-Turner** [comment]
This is now outdated (so much so that 3.8 is EOL). Things are currently fine.

A
