### ISSUE TITLE
Request for Python Triage membership: Jelle Zijlstra

### ISSUE THREAD

**Issue by JelleZijlstra** [python/core-workflow#401]
# Request for Python Triage membership

|     | Description |
| --- | -------------------------- |
| GitHub username   | @JelleZijlstra  |
| bpo username   | Jelle Zijlstra     |
| Additional info   | Maintainer on python/peps, python/typeshed, python/typing, python/mypy, psf/black; triage permissions on bugs.python.org; 24 commits to CPython |

It would be useful for me to be able to manage labels on the CPython repo; it looks like that's the main extra technical role of members of the triage team. I already help review PRs to CPython from time to time.

Some useful links:
* [commits to CPython](https://github.com/python/cpython/commits?author=JelleZijlstra)
* [CPython PR reviews](https://github.com/python/cpython/pulls?q=is%3Apr+reviewed-by%3AJelleZijlstra+is%3Aclosed+)
* [Issues I commented on](https://bugs.python.org/issue?@sort=-activity&@search_text=&@columns=id%2Cactivity%2Ctitle%2Cstatus%2Ccreator&@dispname=Followed%20by%20you&@startwith=0&@group=status&nosy=22444&@filter=nosy&@pagesize=50)

**Comment by terryjreedy** [comment]
Seems if anything overdue.  I count 22 commits since 2017.  GH says 35 reviews. bpo says nosy on 102. 

The main possibly controversial judgements are a) whether to close (reversible) and b) whether a behavior issue that *might* be backported (as decided by the PR committer and possibly other coredevs).

**Comment by Mariatta** [comment]
+1 from me. Thanks @JelleZijlstra for your willingness to help with triaging responsibilities.

Since you're already a member of the Python org, I was able to add you to the Python triage team.

Please see this doc on the Python triage responsibilities and don't hesitate to ask questions.
https://devguide.python.org/tracker/#helptriage

**Comment by JelleZijlstra** [comment]
Thanks @Mariatta!

**Comment by willingc** [comment]
Congrats @JelleZijlstra. Thanks for all of the work that you are doing :sunny:
