### ISSUE TITLE
Do we need both labels "cla-signed" and "cla-not-signed"?

### ISSUE THREAD

**Issue by iritkatriel** [python/core-workflow#453]

**Comment by ezio-melotti** [comment]
I think `CLA not signed` can go, since there are [no open PRs that use it](https://github.com/python/cpython/labels/CLA%20not%20signed).

However there are still [1.2k+ open PRs with the `CLA signed` label](https://github.com/python/cpython/labels/CLA%20signed) so the label is probably needed unless there is a way to reevaluate all those open PRs with the new CLA bot (@ambv?).

If someone needs to prove that the author of a merged PR had signed the CLA, it should be possible to do it even after the labels are removed (the label addition is still in the issue logs, and the signing date can still be compared with the merging date).

**Comment by JelleZijlstra** [comment]
All of these PRs also have the new required "CLA signed" GH Actions check, so I don't think there's much value in keeping it around.

**Comment by ezio-melotti** [comment]
I now removed both labels.
