### ISSUE TITLE
Recolor the version labels

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#495]
# Request for label changes on `python/cpython`

On the CPython repo, we have labels indicating Python versions as: 3.9, 3.10, 3.11, 3.12, etc
Each of these labels have green color.

I think it would be useful to differentiate the color based on the status of the branch.

EOL versions: red
Security only: yellow
bugfix: green
active: blue

to match the colors shown in the status of Python versions https://devguide.python.org/versions/

**Comment by gpshead** [comment]
Agreed, though I don't fully understand what "active: blue" means... is that for the release after the branch is cut but before the .0 release is made in the `["beta1", ".0")` range?   I'd just simplify and reuse "bugfix: green" for that.  It's the RM's decision if something feature related as opposed to a bugfix is allowed to go into the beta/rc branch.

**Comment by CAM-Gerlach** [comment]
Seems okay to me, though it would mean the colors are the same as other labels, making them a little less distinguishable (but probably a minor concern).

> EOL versions: red

AFAIK we don't keep EoL version labels active (at least, we only have security+ labels now) and it would perhaps draw too much attention, so I'm not sure whether we need this. If we do, I'd suggest using the pale red instead which is less attention-grabbing and easier to read the text.



As far as I can tell we 

> Agreed, though I don't fully understand what "active: blue" means... is that for the release after the branch is cut but before the .0 release is made in the `["beta1", ".0")` range

As these are the labels, not the branches, I'm assuming its for the label for the version in the current `main` branch up through, I would assume, either beta1, rc1 or .0 (perhaps beta1 would make the most conceptual sense, since it de-facto has the same status as the bugfix branches absent rm exceptions). So, for example, <kbd>3.12</kbd> right now, and <kbd>3.13</kbd> soon as soon as the 3.12 branch is cut.

**Comment by hugovk** [comment]
We also have the `needs backport to 3.x` labels, which are:

* security only: red
* bugfix: green 

https://github.com/python/cpython/labels?q=needs+backport+to

**Comment by ezio-melotti** [comment]
They are all the same color both to make it more evident that they all belong to the same group (like the `awaiting *` are all yellow, or the `expert-*` are all blue) and also to make it easier to spot version labels by looking for small green labels.  Another (minor) reason is to prevent the issues/PRs lists to look like a Christmas tree.

However being able to differentiate the branch status is a valid use case.  As mentioned by @hugovk, looking at the backport labels is an indirect way to do so.  An alternative would be adding a description to these labels, that can be seen on mouseover, and is less ambiguous than a somewhat arbitrary color scheme.

Would adding a description suffice?

**Comment by Mariatta** [comment]
Adding label description would be a good start. We could add the status (I.e bugfix or security) to the description.

**Comment by ezio-melotti** [comment]
I now updated the descriptions.

**Comment by encukou** [comment]
> Agreed, though I don't fully understand what "active: blue" means...

The devguide names this status `feature` rather than `active`, which is IMO a better term. Or you can use `main`: [since 3.5](https://devguide.python.org/developer-workflow/development-cycle/#in-development-main-branch) that's the one branch with this status.
Anyway, there's no label for the `main` branch, so the terminology isn't relevant here :)

**Comment by CAM-Gerlach** [comment]
> Anyway, there's no label for the `main` branch, so the terminology isn't relevant here :)

It took a couple re-reads, but I'm assuming you're referring to only

> Or you can use `main`: [since 3.5](https://devguide.python.org/developer-workflow/development-cycle/#in-development-main-branch) that's the one branch with this status.

here, rather than

> The devguide names this status `feature` rather than `active`, which is IMO a better term.

Since we do of course have a label for the version corresponding to the `main` branch. `feature` seems more reasonable to me anyway, though I doth bikeshed too much...

**Comment by hugovk** [comment]
I think everything is done here.

* `needs backport to 3.x` are coloured based on bugfix/security status:

<img width="467" alt="image" src="https://github.com/python/core-workflow/assets/1324225/948ad1ca-f066-4a38-b0c7-8ca34be59293">

https://github.com/python/cpython/labels?q=needs+backport

* `3.x` are all the same colour to make it clear they're all the same group (similar to `topic-*`), and have updated descriptions:

<img width="541" alt="image" src="https://github.com/python/core-workflow/assets/1324225/610f0abf-2b2c-4755-b3f4-b1a0771bc430">

https://github.com/python/cpython/labels?q=3

* And there no longer a confusing `active` label: https://github.com/python/cpython/labels/active
