### ISSUE TITLE
Add a setup command to cherry_picker

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#50]
The idea is to simplify the setup by having `cherry_picker` do the checking out of one's fork and setting the origin. It's minor, but it makes getting started easier and it means that if any steps change in the future then people can be unaware as they just need to remember the setup command instead of assuming they know what to do and missing the new step(s).

**Comment by Mariatta** [comment]
I'll look into it. In the meantime, there is a hidden feature that lets you run cherry_picker.py from an existing cpython repo. Maybe it would have helped..
It was introduced in https://github.com/Mariatta/chic_a_cherry_picker/pull/12 by @ncoghlan just needs to be documented  :stuck_out_tongue: 
I prefer keeping a separate checkout just for cherry-picking just so it won't mess up people's real work.

**Comment by ncoghlan** [comment]
https://github.com/python/core-workflow/pull/53 adds some docs around how the script relates to your git remote config (since the way I typically set things up is the exact opposite of the approach we recommend in the developer guide)

However, I do think a setup command would be useful, as that will move us another step closer to being able to automate the whole flow based on a webhook.
