### ISSUE TITLE
Add the topic-tools label

### ISSUE THREAD

**Issue by iritkatriel** [python/core-workflow#516]
We don't have a label for issues related to debugger support and the stuff that's in the Tools/ repo.

**Comment by ezio-melotti** [comment]
There are two options for this:
* If the label is about the `Tools/` dir, it should be [one of the dir-based green ones](https://github.com/python/cpython/labels?q=dir)
* if the label is more generic and includes things that might or might not be in the `Tools/` dir, then it could be a `topic-tools` label

**Comment by iritkatriel** [comment]
Blue topic-tools. It's not just for the Tools/ directory.

**Comment by AlexWaygood** [comment]
I'm confused about whether e.g. Argument Clinic-related issues should have this proposed label applied to them or not. Argument Clinic lives in the `Tools/` directory, on the one hand. But on the other, we already have a specific label for AC issues, and AC issues don't really have anything to do with debuggers.

**Comment by iritkatriel** [comment]
No, I don't think this label covers AC. This is also why it's blue and not green, it's not tied to the directory.

**Comment by AlexWaygood** [comment]
Would `topic-external-tools` be a better name, then?

**Comment by iritkatriel** [comment]
They're not external if they're implemented in Tools/

**Comment by AlexWaygood** [comment]
Which things implemented in `Tools/` would be covered by the label?

**Comment by iritkatriel** [comment]
I don't think we need to get into analysis paralysis here. These labels are not clear-cut categories (should a socket issue be labelled as stdlib or extension-modules? Should an AC issue be interpreter-core or build?)

The labels are useful not because we always know exactly which label to put where, but because they convey useful information.

**Comment by AlexWaygood** [comment]
I'm not trying to get into analysis paralysis. But I don't currently feel like I have a good understanding of what this label would be for, and that means I wouldn't know which issues I should be applying it to when triaging at CPython. I'm trying to understand your "vision" for the label so that I can constructively suggest a better name that I'd find easier to understand :)

**Comment by iritkatriel** [comment]
I'm more interested in having a label for issues related to debugging and debugger support. The stuff in tools can often also fall under interpreter-core or build.

**Comment by iritkatriel** [comment]
But I wouldn't label it topic-debugging because one day we will have an issue about coverage tooling and we won't know where to put it.

**Comment by AlexWaygood** [comment]
Maybe `topic-debuggers`, then? Or `topic-debugging-and-profiling`?

I feel like having "tools" in the name is misleading (even with the different colour), since there are more things in `Tools/` that don't relate to profilers/debuggers than things that do

**Comment by iritkatriel** [comment]
As I wrote above, I don't think we should add a label just for profilers and debugger. It's too narrow.

**Comment by brandtbucher** [comment]
I also don't think the two categories are really related. The stuff in `Tools` and debuggers/profilers are completely different things from a triage/maintenance perspective. They're all just "tools" in an abstract sense.

I don't think it's a problem to introduce two labels: one for the directory, and one for debuggers and profilers. We already have super granular "topic-*" labels; something like `topic-debuggers` would actually be one of the more general labels in the group.

**Comment by gaogaotiantian** [comment]
> @gaogaotiantian, would you find a label like `topic-debuggers` useful?

From my personal perspective, I think the important thing is the purpose of the label (not just for this specific one, the labeling system). Do we need labels to
* Categorize all issues, or
* Find the specific group of people to deal with the issue

For example, `topic-asyncio`, `topic-typing`, `topic-subinterpreters` - they are describing a very specific area of CPython. Without having to read the title and the content of the issue, I would know if I would be interested in it, or even who I should assign it to.

`topic-tools` on the other hand, seems like an effort to "collect some of the uncatetorized issues" to me. Not saying that having it is useless - but I do wonder about the effectivity of the label. Will people realize that the issue is of their interest or in their expertise much faster? `Tools/` is a very large directory and there are plenty of miscellaneous things in it, and some of the contents are probably covered by existing topics (like `Tools/ssl` might be covered by `topic-SSL`?).

`topic-debuggers` or `topic-debuggers-profilers` is a much clearer topic to me and it serves the purpose to narrow the issue down to a specific area that would only interest certain people. I agree it's narrow, but is it narrower than `topic-sqlite3` or `topic-ensurepip`? Or the cutoff is that the topic area has to own a directory in `Lib/`?

That being said, if something like `topic-debuggers-profilers` is created and used, I'll probably monitor the label. If `topic-tools` is used, I'll probably wait for a while and see how we eventually interpret the label.

Again, just sharing my two cents, I don't have a very strong opinion on either label.

**Comment by AlexWaygood** [comment]
> If we add a green `tools` label and a blue `topic-debugging` label, is that ok with everyone?

Yup, that makes sense to me! Though I'd capitalise the T (`Tools` rather than `tools`) to doubly emphasise that it's referring to the name of the directory the code is in rather than an interest area.

**Comment by gaogaotiantian** [comment]
> If we add a green `tools` label and a blue `topic-debugging` label, is that ok with everyone?

Makes sense to me.

**Comment by serhiy-storchaka** [comment]
Don't forget about projects. You can create projects to categorise issues and add fields to categorise issues in the project without increasing the labels list.

**Comment by iritkatriel** [comment]
A new contributor who doesn't know C and is looking for something to do might search for stdlib issues.

**Comment by AlexWaygood** [comment]
> A new contributor who doesn't know C and is looking for something to do might search for stdlib issues.

I'm not sure if any new contributors are actually doing this. But, if that's the theoretical use-case for the `stdlib` label, I think we'd be served better by `language-python` and `language-C` labels.

**Comment by iritkatriel** [comment]
This isn't going anywhere, so I'm closing.
