### ISSUE TITLE
Add label: OS-unsupported

### ISSUE THREAD

**Issue by encukou** [python/core-workflow#526]
# Request for label changes on `python/cpython`

I'm proposing a `OS-unsupported` label, to be used for platforms not listed in [PEP-11](https://peps.python.org/pep-0011/).
If I understand correctly, we can set things up such that labeled issues are automatically added to a [dedicated project](https://github.com/orgs/python/projects/27/views/1), where they can be categorized/handled later. This way, devs/triagers wouldn't need to care about GitHub projects, or “community-supported” platforms. Unless they want to :)

Broader discussion: https://discuss.python.org/t/44621/2

**Comment by erlend-aasland** [comment]
I think this is a very good idea.

**Comment by ezio-melotti** [comment]
> If I understand correctly, we can set things up such that labeled issues are automatically added to a [dedicated project](https://github.com/orgs/python/projects/27/views/1), where they can be categorized/handled later.

There are at least 3 ways this can be automated:
* triagers add the issue to the project directly (can be done from the issue sidebar)
* triagers add a label, and this triggers the addition to the project (what you are suggesting)
* fully automated addition is configured on the project itself 

The last option would be ideal because it requires no human intervention, but it would rely on queries like `in:title <unsupported platform>`.  This will also allow to automatically add the issues on the right view of the project -- something that can't be otherwise automated easily.  The queries might still miss some issues if the platform is not explicitly mentioned, or there might be some false positives, but these can be easily corrected (assuming it still gets most of them right).

> This way, devs/triagers wouldn't need to care about GitHub projects, or “community-supported” platforms. Unless they want to :)

Note that nowadays triagers are able to add issues to project, and can do so from the right sidebar of the issue, just like they add labels.  The downside is that they have to remember that projects exists and have to edit two separate fields (labels and projects) instead of just one (labels).

**Comment by encukou** [comment]
I see no opposition, so I've added the label, and set the project to auto-add labeled issues. Thanks for the thumbs ups everyone :)

(@mhsmith: I labeled an Android issue as `OS-unsupported` to test the auto-add. Hopefully we can label these as `OS-android` [soon](https://github.com/python/core-workflow/issues/524), so I won't go label the other ones.)
