### ISSUE TITLE
Remove `needs backport` label for rejected PRs

### ISSUE THREAD

**Issue by Mariatta** [python/core-workflow#71]
Hi all,

I'm wondering if we can remove the `needs backport to X.Y` label for PRs that were rejected (e.g. closed, but not merged). 

Thanks :)

**Comment by brettcannon** [comment]
Sure.

**Comment by brettcannon** [comment]
I assume this is because you want to look at the backport label to see if anything was forgotten to be backported?

**Comment by Mariatta** [comment]
Thanks. I cleaned up the labels from the closed PRs. I needed an easy way to identify which PRs legitimately need to be backported 😃

**Comment by terryjreedy** [comment]
The labels are speculative for 4 reasons: 1) the patch may never be applied; 2) the patch may be applied 'too late' for a particular version (after it goes off 'bugfix' status, as should be the case soon for 3.5); 3) we may just decide that a particular patch should not be back-ported for particular stability reasons; and 4) backport may require real work that the first committer declines to do.

The labels should be redundant because of the Versions field on the tracker.  So I agree that their best use here is to avoid having backports forgotten.
