### ISSUE TITLE
Turn off code coverage status checks

### ISSUE THREAD

**Issue by brettcannon** [python/core-workflow#76]
https://docs.codecov.io/docs/commit-status#section-disabling-a-status

/cc @haypo

**Comment by haypo** [comment]
I guess that the issue is for CPython. I have no strong opinion on code coverage if it doesn't prevent me to merge changes ;-) In some specific cases, coverage is seen as lower because I added code specific to Windows or macOS whereas coverage is only measured on Linux. Or we need a label or something to confirm that we understand the issue and ignore the coverage regression.

**Comment by brettcannon** [comment]
This issue is to remind me to turn off the status checks so you won't be prevented, even on a phone by the beach (although technically I originally said it should be doable with a tablet 😉 ). This won't turn off code coverage, you just won't get any direct indication in PRs about it anymore.
